services:
  - type: web
    name: lavkush-furniture
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn lavkushfurniture.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: your-secret-key
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-api-secret
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
      - key: ALLOWED_HOSTS
        value: lavkush-furniture.onrender.com
