services:
  - type: web
    name: lavkushfurniture
    env: python
    pythonVersion: 3.10
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn lavkushfurniture.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: lavkushfurniture.onrender.com
      - key: EMAIL_HOST_PASSWORD
        value: your-email-password-here
      - key: CLOUDINARY_CLOUD_NAME
        value: dqsl4l7l2
      - key: CLOUDINARY_API_KEY
        value: 674687165713424
      - key: CLOUDINARY_API_SECRET
        value: DgxOAwtXMgewi-5DrenIuB2X_4U
      - key: CLOUDINARY_URL
        value: cloudinary://674687165713424:DgxOAwtXMgewi-5DrenIuB2X_4U@dqsl4l7l2
